"""Synthetic webshop tracking event generator.

Models a GA4/GTM-style e-commerce event stream (page_view, view_item,
add_to_cart, begin_checkout, purchase) across multiple international
markets, over a 60-day window, with deliberately injected tracking bugs
mirroring real, well-known tracking QA failure modes:

  - A missing 'currency' parameter on purchase events for one market for
    a stretch of days (a common real bug: a market-specific config
    doesn't get the parameter wired up).
  - A duplicate-event-firing bug: purchase events double-fire on a
    subset of days for one market (common real bug: a page reload or a
    misconfigured trigger causes the same conversion to log twice).
  - A silent tracking outage: add_to_cart events stop firing entirely
    for one market for several days (common real bug: a tag fails to
    load, or a consent-mode change blocks it, and nobody notices until
    someone looks at the numbers).
  - Missing 'item_id' on some view_item events (a common data-quality
    issue: a product page doesn't have a valid ID at render time).

Disclosure: this is entirely synthetic tracking data generated by this
script, not real BIRKENSTOCK webshop or Google Analytics data.
"""
import random
from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Optional

MARKETS = ["DE", "US", "UK", "FR", "JP"]
EVENT_TYPES = ["page_view", "view_item", "add_to_cart", "begin_checkout", "purchase"]
CURRENCIES = {"DE": "EUR", "US": "USD", "UK": "GBP", "FR": "EUR", "JP": "JPY"}

START_DATE = date(2026, 6, 1)
N_DAYS = 60

# Injected-bug windows (day offsets from START_DATE), disclosed above.
MISSING_CURRENCY_BUG = {"market": "FR", "days": range(20, 27)}       # 7 days
DUPLICATE_PURCHASE_BUG = {"market": "US", "days": range(35, 39)}     # 4 days
TRACKING_OUTAGE_BUG = {"market": "UK", "days": range(45, 50)}        # 5 days
MISSING_ITEM_ID_RATE = 0.03  # background rate, all markets, all days


@dataclass
class Event:
    event_id: int
    event_date: str
    market: str
    event_type: str
    session_id: str
    item_id: Optional[str]
    currency: Optional[str]
    value: Optional[float]


def _funnel_counts(rng, base_sessions):
    """Realistic e-commerce funnel drop-off: page_view -> view_item ->
    add_to_cart -> begin_checkout -> purchase, each stage a fraction of
    the previous, with natural noise.
    """
    page_view = base_sessions
    view_item = int(page_view * rng.uniform(0.55, 0.70))
    add_to_cart = int(view_item * rng.uniform(0.18, 0.28))
    begin_checkout = int(add_to_cart * rng.uniform(0.45, 0.60))
    purchase = int(begin_checkout * rng.uniform(0.55, 0.72))
    return {
        "page_view": page_view, "view_item": view_item, "add_to_cart": add_to_cart,
        "begin_checkout": begin_checkout, "purchase": purchase,
    }


def generate_events(seed=42):
    rng = random.Random(seed)
    events = []
    event_id = 0

    market_base_sessions = {"DE": 420, "US": 500, "UK": 260, "FR": 190, "JP": 150}

    for day_offset in range(N_DAYS):
        current_date = START_DATE + timedelta(days=day_offset)
        date_str = current_date.isoformat()
        # weekly seasonality: weekends ~20% higher traffic
        weekday_factor = 1.2 if current_date.weekday() >= 5 else 1.0

        for market in MARKETS:
            base = int(market_base_sessions[market] * weekday_factor * rng.uniform(0.9, 1.1))
            counts = _funnel_counts(rng, base)

            outage_active = (
                market == TRACKING_OUTAGE_BUG["market"] and day_offset in TRACKING_OUTAGE_BUG["days"]
            )
            missing_currency_active = (
                market == MISSING_CURRENCY_BUG["market"] and day_offset in MISSING_CURRENCY_BUG["days"]
            )
            duplicate_purchase_active = (
                market == DUPLICATE_PURCHASE_BUG["market"] and day_offset in DUPLICATE_PURCHASE_BUG["days"]
            )

            for etype in EVENT_TYPES:
                n = counts[etype]

                # tracking outage bug: add_to_cart events silently stop
                # firing for the affected market/days
                if outage_active and etype in ("add_to_cart", "begin_checkout", "purchase"):
                    n = 0

                for session_seq in range(n):
                    event_id += 1
                    # A running per-market/day/event-type counter, not a
                    # random draw: an earlier version used
                    # rng.randint(0, base) here, which let two unrelated
                    # sessions on the same day collide onto the same
                    # synthetic session_id purely by chance (a pigeonhole
                    # problem, worse for smaller markets with a smaller
                    # `base`). That produced a spurious "duplicate
                    # purchase" for UK on an untouched day that had
                    # nothing to do with the injected duplicate-purchase
                    # bug — caught by
                    # test_duplicate_purchase_bug_detected asserting
                    # every flagged duplicate falls within the actual
                    # bug's market/day window, not just by eyeballing
                    # the pipeline output.
                    session_id = f"{market}-{day_offset}-{etype}-{session_seq}"

                    item_id = f"BKS-{rng.randint(1000, 9999)}"
                    if etype == "view_item" and rng.random() < MISSING_ITEM_ID_RATE:
                        item_id = None
                    if etype not in ("view_item", "add_to_cart", "begin_checkout", "purchase"):
                        item_id = None

                    currency = CURRENCIES[market]
                    value = None
                    if etype == "purchase":
                        value = round(rng.uniform(35, 220), 2)
                        if missing_currency_active:
                            currency = None

                    events.append(Event(
                        event_id=event_id, event_date=date_str, market=market,
                        event_type=etype, session_id=session_id, item_id=item_id,
                        currency=currency, value=value,
                    ))

                    # duplicate-purchase bug: log the same purchase event twice
                    if etype == "purchase" and duplicate_purchase_active and rng.random() < 0.9:
                        event_id += 1
                        events.append(Event(
                            event_id=event_id, event_date=date_str, market=market,
                            event_type=etype, session_id=session_id, item_id=item_id,
                            currency=currency, value=value,
                        ))

    return events
